# Netlify configuration for GitHub OAuth proxy
[build]
  publish = "dist"
  command = "npm run build"

# Redirect rules for SPA routing
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# GitHub OAuth proxy for Decap CMS
[context.production.environment]
  GITHUB_CLIENT_ID = "YOUR_GITHUB_CLIENT_ID"
  GITHUB_CLIENT_SECRET = "YOUR_GITHUB_CLIENT_SECRET"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"