// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://getnwxzthubdrallsmtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdldG53eHp0aHViZHJhbGxzbXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NTI5MjQsImV4cCI6MjA3MTEyODkyNH0.RsEEhK2mziq_kdkuPnrX1LU_cxzVSa5GnXPDDU9J_bk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});